import React, { useCallback, useContext, useEffect, useMemo, useState } from "react";
import { Alert, Autocomplete, Box, Button, Card, CardContent, CircularProgress, Collapse, FormControl, IconButton, InputLabel, MenuItem, Paper, Select, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Typography } from "@mui/material";
import { ExpandLess, ExpandMore, Refresh, RestartAlt } from "@mui/icons-material";
import { Line } from "react-chartjs-2";
import { CategoryScale, Chart as ChartJS, Legend, LinearScale, LineElement, PointElement, Tooltip } from "chart.js";
import { AuthContext } from "../../contexts/AuthContext";
import "./CellGrowth.css";

ChartJS.register(CategoryScale, Legend, LinearScale, LineElement, PointElement, Tooltip);
const BACKEND_URL = import.meta.env.VITE_BACKEND_URL || "http://127.0.0.1:8000";
export const LEVELS = [{ value: "leader1", label: "Leader 1" }, { value: "leader12", label: "Leader 12" }, { value: "leader144", label: "Leader 144" }, { value: "leader1728", label: "Leader 1728" }];
const today = new Date();
const isoDate = (date) => date.toISOString().slice(0, 10);
const initialFilters = () => ({ startDate: isoDate(new Date(today.getFullYear(), today.getMonth(), 1)), endDate: isoDate(today), entityType: "leader1", leader: null });
const idOf = (leader) => leader?.id || leader?._id || leader?.user_id || "";
const nameOf = (leader) => leader?.name || leader?.fullName || leader?.FullName || leader?.Name || leader?.email || idOf(leader);
const levelOf = (leader) => leader?.level || leader?.entity_type || leader?.hierarchy_level || "-";
const errorMessage = (error) => error?.status === 401 ? "Your session is no longer authorized to view this report." : error?.status === 403 ? "You do not have permission to view this report." : error?.message || "The report could not be loaded.";
const readJson = async (response) => { const text = await response.text(); let body = null; try { body = text ? JSON.parse(text) : null; } catch { body = text; } if (!response.ok) throw Object.assign(new Error(typeof body === "string" ? body : body?.detail || "Request failed"), { status: response.status }); return body; };
const normalizeLeaders = (data) => (Array.isArray(data) ? data : data?.results || data?.leaders || []).map((leader) => ({ ...leader, id: idOf(leader), name: nameOf(leader), level: levelOf(leader) })).filter((leader) => leader.id);

export default function CellGrowth() {
  const { user, authFetch, leaders: cachedLeaders } = useContext(AuthContext);
  const [filters, setFilters] = useState(initialFilters);
  const [leaderOptions, setLeaderOptions] = useState(() => normalizeLeaders(cachedLeaders));
  const [report, setReport] = useState(null); const [loading, setLoading] = useState(false); const [leaderLoading, setLeaderLoading] = useState(false); const [error, setError] = useState(null); const [hasFetched, setHasFetched] = useState(false); const [expanded, setExpanded] = useState({});
  useEffect(() => setLeaderOptions((current) => current.length ? current : normalizeLeaders(cachedLeaders)), [cachedLeaders]);
  const searchLeaders = useCallback(async (query) => { if (!query || query.trim().length < 2) return; setLeaderLoading(true); try { const response = await authFetch(`${BACKEND_URL}/people/search-fast?query=${encodeURIComponent(query.trim())}&limit=25`); setLeaderOptions(normalizeLeaders(await readJson(response))); } catch { /* Search is optional; report errors remain visible. */ } finally { setLeaderLoading(false); } }, [authFetch]);
  const generateReport = useCallback(async (nextFilters = filters) => { setLoading(true); setError(null); setHasFetched(true); setExpanded({}); const query = new URLSearchParams({ start_date: nextFilters.startDate, end_date: nextFilters.endDate, entity_type: nextFilters.entityType }); if (idOf(nextFilters.leader)) query.set("leader_id", idOf(nextFilters.leader)); try { const response = await authFetch(`${BACKEND_URL}/stats/cells-attendance?${query.toString()}`); setReport(await readJson(response)); } catch (requestError) { setReport(null); setError(requestError); } finally { setLoading(false); } }, [authFetch, filters]);
  useEffect(() => { if (user) generateReport(); }, [user]); // eslint-disable-line react-hooks/exhaustive-deps
  const update = (key) => (event, value) => setFilters((current) => ({ ...current, [key]: value }));
  const leaders = report?.leaders || []; const summary = report?.summary || {};
  const chartData = useMemo(() => ({ labels: (report?.timeseries || []).map((item) => item.date), datasets: [{ label: "Attendance", data: (report?.timeseries || []).map((item) => item.attendance), borderColor: "#0f766e", backgroundColor: "rgba(15,118,110,.15)", tension: .3 }, { label: "Unique people", data: (report?.timeseries || []).map((item) => item.unique_people), borderColor: "#e07a5f", backgroundColor: "rgba(224,122,95,.12)", tension: .3 }] }), [report]);
  const chartOptions = { responsive: true, maintainAspectRatio: false, interaction: { mode: "index", intersect: false }, plugins: { legend: { position: "bottom" } }, scales: { y: { beginAtZero: true } } };
  const clearFilters = () => { const next = initialFilters(); setFilters(next); setReport(null); setError(null); setHasFetched(false); };
  const drillDown = (leader) => { const next = { ...filters, leader }; setFilters(next); generateReport(next); };
  if (!user) return <Box className="cell-growth"><Alert severity="warning">You must be signed in to view Cell Attendance.</Alert></Box>;
  return <Box className="cell-growth"><Box className="cell-growth__inner"><Typography variant="overline" color="secondary">Reports / Cell Growth</Typography><Typography variant="h4" className="cell-growth__title">Cell Growth</Typography><Typography color="text.secondary" sx={{ mb: 3 }}>Attendance and cell growth across your leadership hierarchy.</Typography>
    <Paper className="cell-growth__filters"><Stack direction={{ xs: "column", md: "row" }} spacing={2}><TextField type="date" label="Start date" value={filters.startDate} onChange={update("startDate")} InputLabelProps={{ shrink: true }} fullWidth /><TextField type="date" label="End date" value={filters.endDate} onChange={update("endDate")} InputLabelProps={{ shrink: true }} fullWidth /><FormControl fullWidth><InputLabel>Hierarchy level</InputLabel><Select value={filters.entityType} label="Hierarchy level" onChange={update("entityType")}>{LEVELS.map((level) => <MenuItem key={level.value} value={level.value}>{level.label}</MenuItem>)}</Select></FormControl><Autocomplete options={leaderOptions} value={filters.leader} loading={leaderLoading} getOptionLabel={nameOf} isOptionEqualToValue={(option, value) => idOf(option) === idOf(value)} onInputChange={(_, value) => searchLeaders(value)} onChange={update("leader")} renderInput={(params) => <TextField {...params} label="Search leader" />} fullWidth /><Stack direction="row" spacing={1} alignItems="center"><Button variant="contained" startIcon={loading ? <CircularProgress size={18} color="inherit" /> : <Refresh />} onClick={() => generateReport()} disabled={loading || !filters.startDate || !filters.endDate}>Generate</Button><IconButton aria-label="Clear filters" title="Clear filters" onClick={clearFilters}><RestartAlt /></IconButton></Stack></Stack></Paper>
    {error && <Alert severity="error" sx={{ mb: 3 }}>{errorMessage(error)}</Alert>}{loading && <Box className="cell-growth__loading"><CircularProgress /><Typography>Loading report...</Typography></Box>}{!loading && !error && hasFetched && !report && <Alert severity="info">No report data is available for these filters.</Alert>}
    {report && !loading && <><Box className="cell-growth__summary">{[["Total attendance", summary.total_attendance], ["Unique people", summary.unique_people], ["Total cells", summary.total_cells], ["Total leaders", summary.total_leaders]].map(([label, value]) => <Card key={label}><CardContent><Typography color="text.secondary">{label}</Typography><Typography variant="h4" fontWeight={800}>{value ?? 0}</Typography></CardContent></Card>)}</Box>{(report.timeseries || []).length > 0 && <Paper className="cell-growth__chart"><Typography variant="h6">Attendance over time</Typography><Box sx={{ height: { xs: 280, md: 360 }, mt: 2 }}><Line data={chartData} options={chartOptions} /></Box></Paper>}{leaders.length === 0 ? <Alert severity="info">No attendance records or cells match these filters.</Alert> : <Paper className="cell-growth__table"><Table size="small"><TableHead><TableRow><TableCell /><TableCell>Leader</TableCell><TableCell>Hierarchy level</TableCell><TableCell>Total attendance</TableCell><TableCell>Unique attendees</TableCell></TableRow></TableHead><TableBody>{leaders.map((leader) => <React.Fragment key={idOf(leader)}><TableRow hover onClick={() => drillDown(leader)} className="cell-growth__leader-row"><TableCell><IconButton size="small" aria-label={`Show ${nameOf(leader)} cells`} onClick={(event) => { event.stopPropagation(); setExpanded((current) => ({ ...current, [idOf(leader)]: !current[idOf(leader)] })); }}>{expanded[idOf(leader)] ? <ExpandLess /> : <ExpandMore />}</IconButton></TableCell><TableCell>{nameOf(leader)}</TableCell><TableCell>{levelOf(leader)}</TableCell><TableCell>{leader.total_attendance ?? 0}</TableCell><TableCell>{leader.unique_people ?? 0}</TableCell></TableRow><TableRow><TableCell colSpan={5} sx={{ p: 0 }}><Collapse in={expanded[idOf(leader)]}><Table size="small"><TableHead><TableRow><TableCell>Cell name</TableCell><TableCell>Sessions</TableCell><TableCell>Total attendance</TableCell><TableCell>Unique attendees</TableCell><TableCell>Last attendance date</TableCell></TableRow></TableHead><TableBody>{(leader.cells || []).map((cell) => <TableRow key={cell.id}><TableCell>{cell.name}</TableCell><TableCell>{cell.sessions ?? 0}</TableCell><TableCell>{cell.total_attendance ?? 0}</TableCell><TableCell>{cell.unique_people ?? 0}</TableCell><TableCell>{cell.last_attendance_date || "-"}</TableCell></TableRow>)}</TableBody></Table></Collapse></TableCell></TableRow></React.Fragment>)}</TableBody></Table></Paper>}</>}</Box></Box>;
}