import React from "react";
import { Box, Card, Stack, Typography } from "@mui/material";
import { useNavigate, useParams } from "react-router-dom";
import { AreaTrendChart, colors, KpiCardGrid, MultiLineTrendChart, PageFrame, PeriodGranularityControl, ReportDataTable, SectionTitle, StatusChip, Trend } from "../components/ReportingComponents";

const labels = ["Aug 02", "Aug 09", "Aug 16", "Aug 23", "Aug 30"];
const leaders = [{ id: "gavin", name: "Gavin", cells: 4, attendance: 28, average: "7.0", last: "Aug 23 2026" }, { id: "mercia", name: "Mercia", cells: 2, attendance: 15, average: "7.5", last: "Aug 23 2026" }, { id: "david", name: "David", cells: 1, attendance: 8, average: "8.0", last: "Aug 22 2026" }];
const cellRows = [{ id: "springfield-monday", name: "Springfield Monday", day: "Monday", campus: "Springfield", attendance: 18, average: "9.0", trend: 6, sessions: 4 }, { id: "business-friday", name: "Business Friday", day: "Friday", campus: "Central", attendance: 14, average: "7.0", trend: 0, sessions: 4 }, { id: "springfield-thursday", name: "Springfield Thursday", day: "Thursday", campus: "Springfield", attendance: 12, average: "6.0", trend: 15, sessions: 4 }];
const baseColumns = [{ key: "name", label: "LEADER NAME" }, { key: "cells", label: "TOTAL CELLS", numeric: true }, { key: "attendance", label: "TOTAL ATTENDANCE", numeric: true }, { key: "average", label: "AVG ATTENDANCE", numeric: true }, { key: "last", label: "LAST ACTIVE" }, { key: "status", label: "STATUS", render: () => <StatusChip /> }];

function ChartPanel({ title, subtitle, children, footnote }) { return <Card sx={{ bgcolor: colors.panel, border: `1px solid ${colors.border}`, borderRadius: 2, boxShadow: "none", p: 2.5, height: "100%" }}><SectionTitle title={title} subtitle={subtitle} />{children}{footnote && <Typography sx={{ color: colors.muted, fontSize: 12, fontStyle: "italic", mt: 1 }}>{footnote}</Typography>}</Card>; }
function Header({ title, subtitle }) { return <Stack direction={{ xs: "column", lg: "row" }} justifyContent="space-between" alignItems={{ xs: "stretch", lg: "flex-start" }} gap={2} mb={3}><Box><Typography sx={{ fontSize: { xs: 28, md: 34 }, fontWeight: 800 }}>{title}</Typography><Typography sx={{ color: colors.muted }}>{subtitle}</Typography></Box><PeriodGranularityControl /></Stack>; }
function Overview() { const navigate = useNavigate(); return <><Header title="Cells Overview" subtitle="Aggregated cell attendance and leader performance across all campuses." /><KpiCardGrid items={[{ label: "Total Cell Attendance", value: 51, caption: "+8.3% vs last week", tone: colors.green }, { label: "Total Active Cells", value: 5, caption: "across 3 campuses", tone: colors.teal }, { label: "Average per Cell", value: "10.2", caption: "trend positive", tone: colors.blue }, { label: "Active Cell Leaders", value: 3, caption: "Gavin, Mercia, David", tone: colors.orange }]} /><Box sx={{ display: "grid", gridTemplateColumns: { xs: "1fr", lg: "2fr 1fr" }, gap: 2, mb: 2 }}><ChartPanel title="Weekly Attendance Trend" subtitle="Attendance performance by leader over current month" footnote="Note: Aggregate = total cell attendances across all leaders (not unique people)."><MultiLineTrendChart labels={labels} datasets={[{ label: "All Cells (Aggregate)", data: [38, 42, 47, 51, 49], borderColor: colors.teal, borderWidth: 3, tension: .35 }, { label: "Gavin", data: [20, 22, 24, 28, 26], borderColor: "#b18cff", tension: .35 }, { label: "Mercia", data: [10, 12, 13, 15, 15], borderColor: colors.blue, borderDash: [5, 5], tension: .35 }, { label: "David", data: [8, 8, 10, 8, 8], borderColor: colors.orange, tension: .35 }]} /></ChartPanel><ChartPanel title="Weekly Active Cells" subtitle="Total cell counts run per week"><Stack spacing={1.2}>{labels.map((label, index) => <Stack direction="row" justifyContent="space-between" key={label}><Typography sx={{ color: colors.muted }}>{label}, 2026</Typography><StatusChip>{[4, 5, 5, 5, 5][index]} cells</StatusChip></Stack>)}</Stack></ChartPanel></Box><SectionTitle title="Cell Leaders" /><ReportDataTable columns={baseColumns} rows={leaders.map((leader) => ({ ...leader, status: "Active" }))} onRowClick={(row) => navigate(`/reporting/dashboard/${row.id}`)} /></>; }
function LeaderDetail({ leaderId }) { const navigate = useNavigate(); const leader = leaders.find((item) => item.id === leaderId) || leaders[0]; const columns = [{ key: "name", label: "CELL/EVENT NAME" }, { key: "day", label: "DAY" }, { key: "campus", label: "CAMPUS" }, { key: "attendance", label: "ATTENDANCE (PERIOD)", numeric: true }, { key: "average", label: "AVG ATTENDANCE", numeric: true }, { key: "trend", label: "TREND", render: (row) => <Trend value={row.trend} /> }, { key: "sessions", label: "SESSIONS", numeric: true }]; return <><Header title={leader.name} subtitle="Cell Leader Performance Summary & cell group insights." /><KpiCardGrid items={[{ label: "Total Cells", value: leader.cells, caption: "under supervision" }, { label: "Total Attendance", value: leader.attendance, caption: "+12% vs prior period", tone: colors.green }, { label: "Sessions Run", value: 16, caption: "across 4 weeks" }, { label: "Average per Session", value: "7.0", caption: "target 8.0", tone: colors.orange }]} /><ChartPanel title="Cell Performance Over Time" subtitle="Individual performance and combined active cell output" footnote={`Note: Aggregate = total attendances across ${leader.name}'s selected cells.`}><MultiLineTrendChart labels={labels} datasets={[{ label: "Aggregate", data: [8, 10, 12, 14, 15], borderColor: "#fff", borderDash: [4, 4], tension: .35 }, ...cellRows.map((cell, index) => ({ label: cell.name, data: [4 + index, 5 + index, 6 + index, 7 + index, 8 + index], borderColor: [colors.teal, colors.blue, colors.orange][index], tension: .35 }))]} /></ChartPanel><Box mt={2}><SectionTitle title={`${leader.name}'s Cells & Events`} /><ReportDataTable columns={columns} rows={cellRows} onRowClick={(row) => navigate(`/reporting/dashboard/${leader.id}/${row.id}`)} /></Box></>; }
function CellDetail({ leaderId, cellId }) { const leader = leaders.find((item) => item.id === leaderId) || leaders[0]; const cell = cellRows.find((item) => item.id === cellId) || cellRows[0]; const rows = labels.slice(0, 4).map((week, index) => ({ week: `Week ${index + 1}`, date: week + ", 2026", attendance: [4, 6, 5, 8][index], visitors: [1, 0, 2, 1][index], notes: index === 3 ? "Strong turnout" : "-", status: "Completed ✓" })); const columns = [{ key: "week", label: "WEEK" }, { key: "date", label: "DATE" }, { key: "attendance", label: "ATTENDANCE", numeric: true }, { key: "visitors", label: "NEW VISITORS", numeric: true }, { key: "notes", label: "NOTES" }, { key: "status", label: "STATUS", render: (row) => <Typography sx={{ color: colors.green, fontWeight: 700 }}>{row.status}</Typography> }]; return <><Header title={cell.name} subtitle={`${leader.name} · ${cell.campus} Campus · Every ${cell.day} evening.`} /><KpiCardGrid items={[{ label: "Total Attendance", value: cell.attendance, caption: "cumulative for period" }, { label: "Sessions Held", value: "4", caption: "100% completion", tone: colors.green }, { label: "Average Attendance", value: cell.average, caption: "per active session" }, { label: "Trend Rate", value: "+3.2%", caption: "vs last month", tone: colors.orange }]} /><ChartPanel title="Attendance Progression" subtitle="Session attendance count by week"><AreaTrendChart labels={labels} data={[4, 6, 5, 8, 0]} /></ChartPanel><Box mt={2}><SectionTitle title="Weekly Session History" /><ReportDataTable columns={columns} rows={rows} totalRow={{ week: "Total", attendance: 23, visitors: 4, status: "4/4 Complete" }} /></Box></>; }
export default function ReportingDashboard() { const { leaderId, cellId } = useParams(); const leader = leaders.find((item) => item.id === leaderId); const cell = cellRows.find((item) => item.id === cellId); const segments = [{ label: "Cells", to: "/reporting/dashboard" }, { label: "Overall", to: "/reporting/dashboard" }]; if (leader) segments.push({ label: leader.name, to: `/reporting/dashboard/${leader.id}` }); if (cell) segments.push({ label: cell.name }); return <PageFrame segments={segments}>{cellId ? <CellDetail leaderId={leaderId} cellId={cellId} /> : leaderId ? <LeaderDetail leaderId={leaderId} /> : <Overview />}</PageFrame>; }
